// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: permission.sql

package db

import (
	"context"
	"database/sql"
)

const insertNewPermission = `-- name: InsertNewPermission :exec
INSERT INTO permissions (id, service_name, resource, action, attributes, description)
VALUES (UUID(), ?, ?, ?, ?, ?)
`

type InsertNewPermissionParams struct {
	ServiceName string
	Resource    string
	Action      string
	Attributes  string
	Description sql.NullString
}

func (q *Queries) InsertNewPermission(ctx context.Context, arg InsertNewPermissionParams) error {
	_, err := q.db.ExecContext(ctx, insertNewPermission,
		arg.ServiceName,
		arg.Resource,
		arg.Action,
		arg.Attributes,
		arg.Description,
	)
	return err
}
