// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: refresh_token_used.sql

package db

import (
	"context"
)

const createRefreshTokenUsed = `-- name: CreateRefreshTokenUsed :exec
INSERT INTO refresh_tokens_used (id, token_id, refresh_token)
VALUES (?, ?, ?)
`

type CreateRefreshTokenUsedParams struct {
	ID           string
	TokenID      string
	RefreshToken string
}

func (q *Queries) CreateRefreshTokenUsed(ctx context.Context, arg CreateRefreshTokenUsedParams) error {
	_, err := q.db.ExecContext(ctx, createRefreshTokenUsed, arg.ID, arg.TokenID, arg.RefreshToken)
	return err
}
