// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: token.sql

package db

import (
	"context"
)

const createNewToken = `-- name: CreateNewToken :exec
INSERT INTO tokens (id, user_id, session, refresh_token)
VALUES (?, ?, ?, ?)
`

type CreateNewTokenParams struct {
	ID           string
	UserID       string
	Session      string
	RefreshToken string
}

func (q *Queries) CreateNewToken(ctx context.Context, arg CreateNewTokenParams) error {
	_, err := q.db.ExecContext(ctx, createNewToken,
		arg.ID,
		arg.UserID,
		arg.Session,
		arg.RefreshToken,
	)
	return err
}
