// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package wires

import (
	"github.com/go-open-auth/internal/controllers"
	"github.com/go-open-auth/internal/repos"
	"github.com/go-open-auth/internal/services"
)

// Injectors from user_wire.go:

func InitUserRouterHandler() (*controllers.UserController, error) {
	iUserRepo := repos.NewUserRepo()
	iUserAuthRepo := repos.NewUserAuthRepo()
	iUserService := services.NewUserService(iUserRepo, iUserAuthRepo)
	userController := controllers.NewUserController(iUserService)
	return userController, nil
}
